"""add receive_updates to users table

Revision ID: 2b6c961e9dd8
Revises: 35ccaf2ff7f5
Create Date: 2026-06-09 12:42:54.343553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b6c961e9dd8'
down_revision: Union[str, Sequence[str], None] = '35ccaf2ff7f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('receive_updates', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'receive_updates')
    # ### end Alembic commands ###
