"""Initial schema

Revision ID: 44145b8a9318
Revises: 035d572fda7c
Create Date: 2026-06-07 23:45:10.990503

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '44145b8a9318'
down_revision: Union[str, Sequence[str], None] = '035d572fda7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
