"""Add soft delete to User

Revision ID: 51a2f06d6f6d
Revises: 51f424e4b26d
Create Date: 2026-06-10 15:11:41.108116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51a2f06d6f6d'
down_revision: Union[str, Sequence[str], None] = '51f424e4b26d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_system_logs_created_at'), 'system_logs', ['created_at'], unique=False)
    op.drop_index(op.f('idx_oauth_account'), table_name='user_oauth_accounts')
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.create_index(op.f('idx_oauth_account'), 'user_oauth_accounts', ['provider', 'oauth_sub'], unique=False)
    op.drop_index(op.f('ix_system_logs_created_at'), table_name='system_logs')
    # ### end Alembic commands ###
