"""Add auth_provider to RefreshToken

Revision ID: 51f424e4b26d
Revises: 2b6c961e9dd8
Create Date: 2026-06-09 22:39:52.760756

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '51f424e4b26d'
down_revision: Union[str, Sequence[str], None] = '2b6c961e9dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('auth_provider', sa.String(), server_default='local', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'auth_provider')
    # ### end Alembic commands ###
