"""updated system_logs_table

Revision ID: d937551c4d44
Revises: 48addf6ab164
Create Date: 2026-06-07 15:30:55.511365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd937551c4d44'
down_revision: Union[str, Sequence[str], None] = '48addf6ab164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_logs', sa.Column('file', sa.String(), nullable=True))
    op.add_column('system_logs', sa.Column('line', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_logs', 'line')
    op.drop_column('system_logs', 'file')
    # ### end Alembic commands ###
